version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "80:80"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/user/src/app
    depends_on:
      - server
